server:
  port: 8080

spring:
  application:
    name: API-ADMINS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&serverTimezone=GMT
    username: root
    password: abc123456
  cloud:
    nacos:
      discovery:
        # 路径端口号：如果使用linux系统则按linux系统
        server-addr: localhost:8848

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*Mapper.xml